PeerTutor/Models/CourseTutor.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PeerTutor.Models
{
    public class CourseTutor
    {
        public enum Grades
        {
            [Display(Name = "A")] A,
            [Display(Name = "B")] B,
            [Display(Name = "C")] C,
            [Display(Name = "D")] D,
            [Display(Name = "E")] E,


        }
        
        [Required]
        public Grades Grade { get; set; }

        //From User
        [Required]
        [ForeignKey("User")]
        public string UserId { get; set; }

        [ForeignKey("UserId")]
        public virtual ApplicationUser User { get; set; }


        //From Course
        [Required]
        [ForeignKey("Course")]
        public int CourseId { get; set; }
        [ForeignKey("CourseId")]
        public virtual Course Course { get; set; }

        
    }
}

PeerTutor/Controllers/CourseTutorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PeerTutor.Extensions;
using PeerTutor.Models;

namespace PeerTutor.Controllers
{
    public class CourseTutorsController : Controller
    {
        private readonly AppDbContext _context;
      
        public CourseTutorsController(AppDbContext context)
        {
            _context = context;
            
        }

        // GET: CourseTutors
        public async Task<IActionResult> Index()
        {
            //Only show expertise (coursetutors) for the currently logged in user
            var appDbContext = _context.CourseTutors.Include(c => c.Course).Include(c => c.User).Where(c => c.UserId == this.User.FindFirst(ClaimTypes.NameIdentifier).Value.ToString());
            return View(await appDbContext.ToListAsync());
        }

        // GET: CourseTutors/Details/5
        public async Task<IActionResult> Details(string id, int? courseId)
        {
            
            if (id == null || courseId == null)
            {
                return NotFound();
            }

            var courseTutor = await _context.CourseTutors
                .Include(c => c.Course)
                .Include(c => c.User)
                .Where(c => c.UserId == this.User.FindFirst(ClaimTypes.NameIdentifier).Value.ToString()) //only show for currently logged in user
                .Where(c => c.CourseId == courseId)
                .FirstOrDefaultAsync(m => m.UserId == id);
            if (courseTutor == null)
            {
                return RedirectToAction("Index").WithWarning("You were redirected!", "The action you requested was not allowed and thus could not be completed.");
            }
            return View(courseTutor);
        }

        // GET: CourseTutors/Create
        public IActionResult Create()
        {
            //ViewData["CourseId"] = new SelectList(_context.Courses, "Id", "Id");
            //ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id");
            ViewData["CourseId"] = new SelectList(_context.Courses, "Id", "CourseTitle");
            ViewData["UserId"] = this.User.FindFirst(ClaimTypes.NameIdentifier).Value.ToString();

            return View();
        }

        // POST: CourseTutors/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Grade,UserId,CourseId")] CourseTutor courseTutor)
        {
            if (ModelState.IsValid)
            {

                _context.Add(courseTutor);
                try
                {
                    await _context.SaveChangesAsync();
                }
                catch (Exception ex)
                {
                    if (ex != null)
                    {
                        return RedirectToAction("Create").WithWarning("You tried to add a course you've already added.",  "Please select a different course.");
                    }
                    //return View(courseTutor);
                    //This either returns a error string, or null if it can’t handle that error
                    
                    throw; //couldn’t handle that error, so rethrow
                }
                
                return RedirectToAction(nameof(Index));
            }
            //ViewData["CourseId"] = new SelectList(_context.Courses, "Id", "Id", courseTutor.CourseId);
            //ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", courseTutor.UserId);
            ViewData["CourseId"] = new SelectList(_context.Courses, "Id", "CourseTitle");
            ViewData["UserId"] = this.User.FindFirst(ClaimTypes.NameIdentifier).Value.ToString();

            return View(courseTutor);
        }

        // GET: CourseTutors/Edit/5
        public async Task<IActionResult> Edit(string id, int? courseId)
        {
            if (id == null || courseId == null)
            {
                return NotFound();
            }

            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value.ToString();

            if (id != userId)
            {

                return RedirectToAction("Index").WithWarning("You were redirected!", "The action you requested was invalid!");
            }

            var courseTutor = await _context.CourseTutors.FindAsync(id, courseId);
            if (courseTutor == null)
            {
                return NotFound();
            }
            ViewData["CourseId"] = new SelectList(_context.Courses, "Id", "Id", courseTutor.CourseId);
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", courseTutor.UserId);
            return View(courseTutor);
        }

        // POST: CourseTutors/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Grade,UserId,CourseId")] CourseTutor courseTutor)
        {
            if (id != courseTutor.UserId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(courseTutor);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CourseTutorExists(courseTutor.UserId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CourseId"] = new SelectList(_context.Courses, "Id", "Id", courseTutor.CourseId);
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", courseTutor.UserId);
            return View(courseTutor);
        }

        // GET: CourseTutors/Delete/5
        public async Task<IActionResult> Delete(string id, int? courseId)
        {
            if (id == null || courseId == null)
            {
                return NotFound();
            }
            
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value.ToString();

            if (id != userId)
            {

                return RedirectToAction("Index").WithWarning("You were redirected!", "The action you hit has bounced you back to Index!");
            }
            var courseTutor = await _context.CourseTutors
                .Include(c => c.Course)
                .Include(c => c.User)
                .FirstOrDefaultAsync(m => m.UserId == id);
            if (courseTutor == null)
            {
                return NotFound();
            }

            return View(courseTutor);
        }

        // POST: CourseTutors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id, int? courseId)
        {
            var courseTutor = await _context.CourseTutors.FindAsync(id, courseId);
            _context.CourseTutors.Remove(courseTutor);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CourseTutorExists(string id)
        {
            return _context.CourseTutors.Any(e => e.UserId == id);
        }

        [HttpGet]
        public async Task<IActionResult> ShowExperts(int courseId)
        {
            //var appDbContext = _context.CourseTutors.Include(c => c.Course).Include(c => c.User).Where(c => c.UserId == this.User.FindFirst(ClaimTypes.NameIdentifier).Value.ToString());
            var courseTutors = await _context.CourseTutors
                .Include(c => c.User)
                //nclude(c => c.User.Ratings)
                .Include(c => c.User.ReviewsFor)
                .Include(c => c.Course)
                .Where(c => c.CourseId == courseId).ToListAsync();


            //var courseTutor = await _context.CourseTutors
            //    .Include(c => c.Course)
            //    .Include(c => c.User)
            //    .Where(c => c.UserId == this.User.FindFirst(ClaimTypes.NameIdentifier).Value.ToString()) //only show for currently logged in user
            //    .Where(c => c.CourseId == courseId)
            //    .FirstOrDefaultAsync(m => m.UserId == this.User.FindFirst(ClaimTypes.NameIdentifier).Value.ToString());

            //courseTutors.Remove(courseTutor);

            ViewData["CourseTitle"] = _context.Courses.Find(courseId).CourseTitle;
                

            return View("Experts", courseTutors);
        }
    }
}

PeerTutor/Controllers/ReviewsController.cs
using System;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PeerTutor.Models;
using PeerTutor.ViewModels;
using System.Linq;
using PeerTutor.Extensions;

namespace PeerTutor.Controllers
{
    public class ReviewsController : Controller
    {
        private readonly AppDbContext _context;
        public ReviewsController(AppDbContext context)
        {
            _context = context;
        }
        // GET: Review
        public async Task<IActionResult> Index()
        {
            var appDbContext = _context.Reviews.Include(s => s.Reviewed).Include(s => s.Reviewer)
                .Where(c => (c.ReviewerId == this.User.FindFirst(ClaimTypes.NameIdentifier).Value.ToString() || c.RevieweeId == this.User.FindFirst(ClaimTypes.NameIdentifier).Value.ToString()));
            return View(await appDbContext.ToListAsync());
        }

        // GET: Review/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var review = await _context.Reviews
                .Include(s => s.Reviewer)
                .Include(s => s.Reviewed)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (review == null)
            {
                return NotFound();

            }

            return View(review);
        }

        // GET: Review/Create
        public IActionResult Create(string RevieweeId)
        {
            bool isAjaxCall = Request.Headers["x-requested-with"] == "XMLHttpRequest";

            //if (RevieweeId == this.User.FindFirst(ClaimTypes.NameIdentifier).Value.ToString())
            //{
            //    return RedirectToAction("Index", "Sessions").WithWarning("Awesome!", "You cannot leave a review for yourself.");
            //}

            if (isAjaxCall)
            {
                //TODO: Improve logic here to only allow one review for each session. Will need to tie reviews to session.

                var reviewer = this.User.FindFirst(ClaimTypes.NameIdentifier).Value.ToString();
                ViewBag.ReviewerId = reviewer;

                ViewBag.RevieweeId = RevieweeId;
                var model = new Review { ReviewerId = reviewer, RevieweeId = RevieweeId };

                return PartialView("_AddReview", model);
            }
            
            return RedirectToAction("Index", "Sessions").WithWarning("Awesome!", "Click review on a past session to leave a review.");
        }

        // POST: Review/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task <IActionResult> Create([Bind("ReviewContent, RevieweeId, ReviewerId, Stars")] Review userReview)
        {
            // TODO: Add insert logic here

            if (ModelState.IsValid)
            {

                try
                {
                    var review = new Review { ReviewContent = userReview.ReviewContent, ReviewerId = userReview.ReviewerId , RevieweeId = userReview.RevieweeId, ReviewDate = userReview.ReviewDate, Stars = userReview.Stars };

                    _context.Add(review);
                    await _context.SaveChangesAsync();

                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    return View(ex.Message);
                }
            }

            //ModelState.AddModelError("", "Error");
            return PartialView("_AddReview", userReview);
        }

        // GET: Review/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Review/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Review/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Review/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

    
        public async Task<IActionResult> ShowReviews(string userId)
        {
            var reviews = _context.Reviews.Include(s => s.Reviewed).Include(c => c.Reviewer).Where(c => c.RevieweeId == userId);

            return PartialView("ShowReviews", await reviews.ToListAsync());
            

        }
    }
}

PeerTutor/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PeerTutor.Models;
using PeerTutor.ViewModels;

namespace PeerTutor.Controllers
{
    public class UsersController : Controller
    {
        private readonly AppDbContext _context;

        public UsersController(AppDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reviewsFor = _context.Reviews
                .Include(s => s.Reviewed)
                .Include(c => c.Reviewer)
                .Where(c => c.RevieweeId == id);

            var reviewsBy =  _context.Reviews
                .Include(s => s.Reviewed)
                .Include(c => c.Reviewer)
                .Where(c => c.ReviewerId == id);

            var user = await _context.Users
                .Include(s => s.ReviewsBy)
                .Include(s => s.ReviewsFor)
                .FirstOrDefaultAsync(m => m.Id == id);

            var model = new UserViewModel
            {
                Id = user.Id,
                UserName = user.UserName,
                Photo = user.Photo,
                FirstName = user.FirstName,
                LastName = user.LastName,
                ClassYear = user.ClassYear,
                RateCount = user.RateCount,
                RateTotal = user.RateTotal,
                ReviewsFor = reviewsFor.ToList(),
                ReviewsBy = reviewsBy.ToList()



            };
            return View(model);
        }

        [HttpGet]
        public JsonResult GetEvents(string id)
        {

            var sessions = _context.Session.Include(c => c.Booked)
                .Include(c => c.Booker)
                .Where(c => c.BookedId == id || c.BookerId == id);

            var events = new List<SessionViewModel>();
            
            foreach ( Session session in sessions)
            {
                events.Add(new SessionViewModel()
                {
                    Id = session.Id,
                    Topic = session.Topic,
                    Start = session.StartTime.ToString(),
                    End = session.EndTime.ToString()
                });
            }

            return Json(events.ToArray());
        }
    }
}

PeerTutor/Views/CourseTutors/Create.cshtml
@model PeerTutor.Models.CourseTutor

@{
    ViewData["Title"] = "Add Expertise";
}

<h4>Add Expertise</h4>
<hr />
<div class="row">
    <div class="col-md-8">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group row">
                <label asp-for="Grade" class="control-label col-md-2"></label>
                <select asp-for="Grade" class="form-control col-md-6" asp-items="Html.GetEnumSelectList<CourseTutor.Grades>()"></select>
                <span asp-validation-for="Grade" class="text-danger"></span>
            </div>
            <div class="form-group row">
                <input type="hidden" name="UserId" class="form-control" value="@ViewBag.UserId" />
            </div>
            <div class="form-group row">
                <label asp-for="Course" class="control-label col-md-2"></label>
                <select asp-for="CourseId" class="form-control col-md-6" asp-items="ViewBag.CourseId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn-link">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PeerTutor/Views/CourseTutors/Delete.cshtml
@model PeerTutor.Models.CourseTutor

@{
    ViewData["Title"] = "Delete Expertise";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this expertise?</h3>
<div>
    
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Grade)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Grade)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.User.FirstName)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Course)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Course.CourseTitle)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="UserId" />
        <input type="hidden" asp-for="CourseId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index" class="btn-link">Back to List</a>
    </form>
</div>

PeerTutor/Views/CourseTutors/Details.cshtml
@model PeerTutor.Models.CourseTutor

@{
    ViewData["Title"] = "Expertise Details";
}

<h1>Details</h1>

<div>
    
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Grade)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Grade)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.User.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Course)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Course.CourseTitle)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { id=Model.UserId, courseId = Model.CourseId}) |
    <a asp-action="Index">Back to List</a>
</div>

PeerTutor/Views/CourseTutors/Edit.cshtml
@model PeerTutor.Models.CourseTutor

@{
    ViewData["Title"] = "Edit Expertise";
}

<h1>Edit</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Grade" class="control-label"></label>
                <select asp-for="Grade" class="form-control" asp-items="Html.GetEnumSelectList<CourseTutor.Grades>()"></select>
                <span asp-validation-for="Grade" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="UserId" />
            <input type="hidden" asp-for="CourseId" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn-link">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PeerTutor/Views/CourseTutors/Experts.cshtml
@model IEnumerable<PeerTutor.Models.CourseTutor>



@{
    ViewData["Title"] = "Experts";
    var imageThumbPath = "/images/default_image.jpg";

}

@*<h2 class="mt-5 text-center">Experts - </h2>*@
<h4 class="text-center">Experts - @ViewData["CourseTitle"]</h4>

@if (!Model.Any())
{
    <div class="alert alert-info alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <strong>😞</strong> There are currently no experts available. Please check back soon!
    </div>

}



<div class="card-deck" id="experts">
    @foreach (var expert in Model)
    {
        @*<div class="col-auto mb-3">*@
    <div class="card">
        <a href="@Url.Action("Details","Users", new { id = @expert.User.Id })">
        <img class="card-img-top" src="@{if (string.IsNullOrEmpty(expert.User.Photo))
            {@imageThumbPath }
            else { @expert.User.Photo; }
            }"/>
            </a>
        <div class="card-body">
            <div class="card-text text-center">
                <!-- Button trigger modal -->

                <h3>@Html.ActionLink(@expert.User.FirstName, "Details", "Users", new { id = @expert.UserId }, new { @class = "btn-link" }) </h3>
                <div>
                    <img src="~/images/StarFade.gif" alt="Star Rating" align="middle" id="1" class="rating" />
                    <img src="~/images/StarFade.gif" alt="Star Rating" align="middle" id="2" class="rating" />
                    <img src="~/images/StarFade.gif" alt="Star Rating" align="middle" id="3" class="rating" />
                    <img src="~/images/StarFade.gif" alt="Star Rating" align="middle" id="4" class="rating" />
                    <img src="~/images/StarFade.gif" alt="Star Rating" align="middle" id="5" class="rating" />
                    <span style="vertical-align: bottom;">(@expert.User.RateCount)</span> @{if (expert.User.RateCount > 0)
                        {
                            decimal a = @expert.User.RateTotal / @expert.User.RateCount; <span class="avr mb-1" style="display:none;"> @a</span> } }<br />
                </div>



                <h3>Grade: @expert.Grade</h3>

                @Html.ActionLink("Book me!", "Create", "Sessions", new { bookedWith = expert.UserId, courseId = expert.CourseId }, new { @class = "btn btn-info mb-1" })

                <button type="button" class="btn btn-primary mb-1" data-toggle="ajax-modal" data-target="#add-review" data-url="@Url.Action("ShowReviews", "Reviews", new { userId = expert.UserId})">
                    Reviews
                </button>

            </div>
        </div>

    </div>
    }
</div>

<!-- Button trigger modal -->
@*<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#add-contact" id="reviews">
    Add contact
</button>*@
<!-- Modal placeholder -->
<div id="modal-placeholder"></div>


@section Scripts{

    <script>
        $('#experts > div > div > div > div').each(function () {

            var av = $(this).find("span.avr").text();

            if (av != "" || av != null) {
                // alert(av);
                // fillRating(parseInt(av));
                var img = $(this).find("img[id='" + parseInt(av) + "']");
                img.attr("src", "/images/starGlow.gif").prevAll("img.rating").attr("src", "/images/starGlow.gif");
            }

        });



    </script>

    <script>
        $(function () {
    $('button[data-toggle="ajax-modal"]').click(function (event) {
        var url = $(this).data('url');
        $.get(url).done(function (data) {
            $('#modal-placeholder').html(data);
            $('#modal-placeholder > .modal').modal('show').css({ "max-height": screen.height * .8, "overflow-y": "auto" });
        });
    });
});
        //$(function () {
        //    $("img.rating").mouseover(function () {
        //        var placeholderElement = $('#modal-placeholder');

        //        $('button[data-toggle="ajax-modal"]').click(function (event) {
        //            var url = $(this).data('url');
        //            $.get(url).done(function (data) {
        //                placeholderElement.html(data);
        //                placeholderElement.find('.modal').modal('show');
        //            });
        //        });
        //    })
        //});
    </script>
}

PeerTutor/Views/CourseTutors/Index.cshtml
@model IEnumerable<PeerTutor.Models.CourseTutor>

@{
    ViewData["Title"] = "Expertise";
}

<h1>My Expertise</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Grade)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.User)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Course)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Grade)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.User.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Course.CourseTitle)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.UserId, courseId = item.CourseId }, new { @class = "btn-link" }) |
                @Html.ActionLink("Details", "Details", new { id = item.UserId, courseId = item.CourseId }, new { @class = "btn-link" })  |
                @Html.ActionLink("Delete", "Delete", new { id = item.UserId, courseId = item.CourseId }, new { @class = "btn-link" })
            </td>
        </tr>
}
    </tbody>
</table>