PeerTutor/ViewModels/CreateRoleViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace PeerTutor.ViewModels
{
    public class CreateRoleViewModel
    {
        [Required]
        [Display(Name = "Role Name")]
        public string RoleName { get; set; }
    }
}

PeerTutor/ViewModels/EditRoleViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace PeerTutor.ViewModels
{
    public class EditRoleViewModel 
    {
        public EditRoleViewModel()
        {
            Users = new List<string>();
        }

        public string Id { get; set; }
        [Required(ErrorMessage = "Role Name is required")]
        [Display(Name = "Role Name")]
        public string RoleName { get; set; }

        public List<string> Users { get; set; }
    }
}

PeerTutor/Controllers/AdministrationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using PeerTutor.Models;
using PeerTutor.ViewModels;

namespace PeerTutor.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AdministrationController : Controller
    {
        private readonly RoleManager<IdentityRole> roleManager;
        private readonly UserManager<ApplicationUser> userManager;

        public AdministrationController(RoleManager<IdentityRole> roleManager,
            UserManager<ApplicationUser> userManager)
        {
            this.roleManager = roleManager;
            this.userManager = userManager;
        }

        public IActionResult Index()
        {
            return RedirectToAction("listroles", "administration");


        }

        [HttpGet]
        public IActionResult ListUsers()
        {
            var users = userManager.Users;

            return View(users);
        }
        [HttpGet]
        public IActionResult ListRoles()
        {
            var roles = roleManager.Roles;

            return View(roles);
        }

        [HttpGet]
        public IActionResult CreateRole()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateRole(CreateRoleViewModel model)
        {
            if (ModelState.IsValid)
            {
                IdentityRole identityRole = new IdentityRole
                {
                    Name = model.RoleName
                };

                IdentityResult result = await roleManager.CreateAsync(identityRole);

                if (result.Succeeded)
                {
                    TempData["Message"] = "Role Added!";
                    return RedirectToAction("listroles", "administration");
                }

                foreach (IdentityError error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }



            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> EditRole(string id)
        {
            var role = await roleManager.FindByIdAsync(id);

            if (role == null)
            {
                ViewBag.ErrorMessage = $"Role with Id = {id} cannot be found";
                return View("NotFound");
            }
            var model = new EditRoleViewModel
            {
                Id = role.Id,
                RoleName = role.Name
            };

            foreach (var user in userManager.Users)
            {
                if (await userManager.IsInRoleAsync(user, role.Name))
                {
                    model.Users.Add(user.UserName);
                }
            }
            return View(model);

        }

        [HttpPost]
        public async Task<IActionResult> EditRole(EditRoleViewModel model)
        {
            var role = await roleManager.FindByIdAsync(model.Id);

            if (role == null)
            {
                ViewBag.ErrorMessage = $"Role with Id = {model.Id} cannot be found";
                return View("NotFound");
            }
            else
            {
                role.Name = model.RoleName;
                var result = await roleManager.UpdateAsync(role);

                if (result.Succeeded)
                {
                    return RedirectToAction("ListRoles");
                }


                //The same error was being output twice and I couldn't figure out why so I picked FirstorDefault. Code for the iteration is commented out below.
                ModelState.AddModelError("", result.Errors.FirstOrDefault().Description);


                //foreach(var error in result.Errors)
                //{
                //    ModelState.AddModelError("", error.Description);
                //}
                return View(model);
            }



        }

        [HttpGet]
        public async Task<IActionResult> EditUsersInRole(string roleId)
        {
            ViewBag.roleId = roleId;
            var role = await roleManager.FindByIdAsync(roleId);

            if (role == null)
            {
                ViewBag.ErrorMessage = $"Role with Id = {roleId} cannot be found";
                return View("NotFound");
            }

            var model = new List<UserRoleViewModel>();

            foreach (var user in userManager.Users)
            {
                var userRoleViewModel = new UserRoleViewModel
                {
                    UserId = user.Id,
                    UserName = user.UserName
                };

                if (await userManager.IsInRoleAsync(user, role.Name))
                {
                    userRoleViewModel.IsSelected = true;
                }
                else
                {
                    userRoleViewModel.IsSelected = false;

                }

                model.Add(userRoleViewModel);

            }
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> EditUsersInRole(List<UserRoleViewModel> model, string roleId)
        {
            var role = await roleManager.FindByIdAsync(roleId);

            if (role == null)
            {
                ViewBag.ErrorMessage = $"Role with Id = {roleId} cannot be found";
                return View("NotFound");
            }

            for (int i = 0; i < model.Count; i++)
            {
                var user = await userManager.FindByIdAsync(model[i].UserId);

                IdentityResult result;

                if (model[i].IsSelected && !(await userManager.IsInRoleAsync(user, role.Name)))
                {
                    result = await userManager.AddToRoleAsync(user, role.Name);
                }
                else if (!model[i].IsSelected && await userManager.IsInRoleAsync(user, role.Name))
                {
                    result = await userManager.RemoveFromRoleAsync(user, role.Name);
                }
                else
                {
                    continue;
                }

                if (result.Succeeded)
                {
                    if (i < (model.Count - 1))
                        continue;

                    else
                        return RedirectToAction("EditRole", new { Id = roleId });
                }
            }



            return RedirectToAction("EditRole", new { Id = roleId });
        }
    }
}

PeerTutor/Views/Administration/CreateRole.cshtml
@model CreateRoleViewModel
@{
    ViewBag.Title = "Create New Role";
}

<h1>@ViewData["Title"]</h1>


@*@if(Model.Message != null)
    {
        <div class="alert alert-info">@Model.Message</div>
    }*@

<div class="row">
    <div class="col-md-4">
        <form method="post">
            
            <hr />
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="RoleName"></label>
                <input asp-for="RoleName" class="form-control" />
                <span asp-validation-for="RoleName" class="text-danger"></span>
            </div>


            <button type="submit" class="btn btn-primary">Create Role</button>
        </form>
    </div>
</div>


@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

PeerTutor/Views/Administration/EditRole.cshtml
@model EditRoleViewModel

@{ 
    ViewBag.Title = "Edit Role";

}

<h1>Edit Role</h1>

    <form method="post" class="mt-3">

        <div class="form-group row">
            <div class="col-sm-1"><label asp-for="Id" class="col-form-label"></label></div>
            <div class="col-sm-11">
                <input asp-for="Id" disabled class="form-control" />
            </div>
        </div>
        <div class="form-group row">
            <div class="col-sm-1" ><label asp-for="RoleName" class="col-form-label"></label></div>
            <div class="col-sm-11">
                <input asp-for="RoleName" class="form-control" />
                <span asp-validation-for="RoleName" class="text-danger"></span>
            </div>
        </div>

        <div asp-validation-summary="All" class="text-danger"></div>

        <div class="form-group-row">
            <div class="col-sm-10">
                <button type="submit" class="btn btn-primary">Update</button>
                <a asp-action="ListRoles" class="btn btn-danger">Cancel</a>
            </div>
        </div>
        <br />


        <div class="card">
            <div class="card-header">
                <h3>Users in this role</h3>
            </div>
            <div class="card-body">
                @if (Model.Users.Any())
                {
                    @foreach (var user in Model.Users)
                    {
                        <h5 class="card-title">@user</h5>
                    }
                }
                else
                {
                    <h5 class="card-title">None at the moment</h5>
                }

            </div>
            <div class="card-footer">
                <a asp-action="EditUsersInRole" asp-controller="Administration" asp-route-roleId="@Model.Id" class="btn btn-primary" style="width:auto">Add or Remove Users</a>
            </div>
        </div>
    </form>

PeerTutor/Views/Administration/EditUsersInRole.cshtml
@model List<UserRoleViewModel>

@{ 
    var roleId = ViewBag.roleId; 
}


    <form method="post">
        <div class="card">
            <div class="card-header">
                <h2>Add or remove users from this role</h2>
            </div>

            <div class="card-body">
                @for (int i = 0; i < Model.Count; i++)
                {
                <div class="form-check m-1">
                    <input type="hidden" asp-for="@Model[i].UserId" />
                    <input type="hidden" asp-for="@Model[i].UserName" />
                    <input asp-for="@Model[i].IsSelected" class="form-check-input" />
                    <label class="form-check-label" asp-for="@Model[i].IsSelected">
                        @Model[i].UserName
                    </label>
                </div>
                }

            </div>

            <div class="card-footer">
                <input type="submit" value="Update" class="btn btn-primary" style="width:auto"  />
                <a asp-action="EditRole" asp-route-id="@roleId" class=btn btn-primary" style="width:auto">Cancel</a>
            </div>

        </div>
    </form>

PeerTutor/Views/Administration/ListRoles.cshtml
@using Microsoft.AspNetCore.Identity



@model IEnumerable<IdentityRole>


@{
    ViewBag.Title = "All Roles";

}

<h1> All Roles</h1>


@if (TempData["Message"] != null)
{
    <div class="alert alert-info">@TempData["Message"]</div>
}


@if (Model.Any())

{
    <a class="btn btn-primary mb-3" style="width:auto" asp-action="CreateRole" asp-controller="administration">Add new role</a>

    foreach (var role in Model)
    {
        <div class="card mb-3">
            <div class="card-header">
                Role Id : @role.Id
            </div>
            <div class="card-body">
                <h5 class="card-title">@role.Name</h5>
            </div>
            <div class="card-footer">
                <a class="btn btn-primary" asp-action="EditRole" asp-controller="administration" asp-route-id="@role.Id">Edit</a>
                <a href="#" class="btn btn-danger">Delete</a>
            </div>
        </div>
    }

}
else
{
    <div class="card">
        <div class="card-header">
            No roles created yet
        </div>
        <div class="card-body">
            <h5 class="card-title">
                Use the button below to create a Role
            </h5>
            <a class="btn btn-primary" style="width:auto" asp-controller="administration" asp-action="CreateRole">
                Create Role
            </a>
        </div>
    </div>
}

PeerTutor/Views/Administration/ListUsers.cshtml
@using Microsoft.AspNetCore.Identity



@model IEnumerable<ApplicationUser>


@{
    ViewBag.Title = "All Users";

}



@if (TempData["Message"] != null)
{
    <div class="alert alert-info">@TempData["Message"]</div>
}



<div class="row">
    <div class="col-lg-12 text-center">
        <h2 class="mt-5">All Users</h2>
    </div>
</div>


<input type="text" id="myInput" onkeyup="myFunction()" placeholder="Search for users by first name. . ."
       title="Type in a company name">

<table id="myTable">
    <thead>
        <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>User Name/Email</th>
            <th>Class Year</th>
        </tr>
    </thead>
    <tbody>

        @if (Model.Any())

        {
            //<a class="btn btn-primary mb-3" style="width:auto" asp-action="CreateRole" asp-controller="administration">Add new role</a>

            foreach (var user in Model)
            {

                <tr>
                    <td>@user.FirstName</td>
                    <td>@user.LastName</td>
                    <td>@user.UserName</td>
                    <td>@user.ClassYear</td>
                </tr>

            }






        }

    </tbody>
</table>




@if (!Model.Any())
{
    <div class="card">
        <div class="card-header">
            No users created yet
        </div>
    </div>
}


@section Scripts {
    <script>
        function myFunction() {
        var input, filter, table, tr, td, i, txtValue;
        input = document.getElementById("myInput");
        filter = input.value.toUpperCase();
        table = document.getElementById("myTable");
        tr = table.getElementsByTagName("tr");
        for (i = 0; i < tr.length; i++) {
            td = tr[i].getElementsByTagName("td")[0];
            if (td) {
                txtValue = td.textContent || td.innerText;
                if (txtValue.toUpperCase().indexOf(filter) > -1) {
                    tr[i].style.display = "";
                } else {
                    tr[i].style.display = "none";
                }
            }
        }
    }
    </script>
}